<?php

return [
    'name' => 'Dilshan Senanayaka',
    'initials' => 'DS',
    'headline' => ['Building Clean, Reliable', 'Digital Solutions'],
    'tagline' => 'Detail-oriented and enthusiastic developer focused on building clean, reliable solutions with modern web technologies like Next.js, Laravel, WordPress, and React Native.',
    'status' => 'Full Stack Developer',
    'hero_badge' => 'Full Stack Developer',
    'roles' => [
        'Full Stack Developer',
        'Next.js',
        'Laravel',
        'WordPress',
        'React Native',
    ],
    'about' => [
        'bio' => 'A detail-oriented and enthusiastic Full Stack Developer based in Colombo, Sri Lanka, combining clean engineering practices with a love for teaching to build impactful digital experiences. Currently working at Litus Group, building full-stack solutions with modern web technologies. Previously worked as a Junior Software Developer at M Data Zone SA Pvt Ltd, delivering Next.js, Payload CMS, WordPress, and e-commerce platforms. Earlier contributed as a Software Engineering Intern at the Sri Lanka Export Development Board, delivering Laravel-based platforms and a React Native CRM app used by real teams. Holds a BICT (Hons) degree in Software Technology from the University of Sri Jayewardenepura.',
        'experience' => '2+ years',
        'location' => 'Colombo, Sri Lanka',
        'focus_areas' => [
            'Web development',
            'Frontend engineering',
            'Clean architecture',
            'Database design',
            'Teaching & mentoring',
            'Problem solving',
        ],
        'current_interest' => 'Backend engineering, data-focused systems, and sharing knowledge through teaching',
    ],
    'skills' => [
        [
            'title' => 'Programming & Scripting',
            'icon' => 'code',
            'color' => 'blue',
            'skills' => ['JavaScript', 'TypeScript', 'PHP', 'Python', 'Java', 'Dart (Flutter)'],
        ],
        [
            'title' => 'Web Development',
            'icon' => 'code',
            'color' => 'cyan',
            'skills' => ['Next.js', 'React.js', 'Laravel', 'WordPress', 'WooCommerce', 'Elementor', 'HTML5', 'CSS3', 'Tailwind CSS'],
        ],
        [
            'title' => 'Mobile App Development',
            'icon' => 'boxes',
            'color' => 'cyan',
            'skills' => ['React Native', 'Android Studio (Java/Kotlin)'],
        ],
        [
            'title' => 'Databases & Backend',
            'icon' => 'database',
            'color' => 'teal',
            'skills' => ['MySQL', 'Firebase', 'Payload CMS', 'API development & integration'],
        ],
        [
            'title' => 'Authentication & Security',
            'icon' => 'badge',
            'color' => 'indigo',
            'skills' => ['JWT (Bearer & Self-signed)', 'Refresh Tokens', 'OTP-based auth', 'API Tokens'],
        ],
        [
            'title' => 'DevOps & Tools',
            'icon' => 'wrench',
            'color' => 'blue',
            'skills' => ['Git', 'GitHub', 'VS Code', 'Postman'],
        ],
    ],
    'soft_skills' => [
        'Problem Solving & Analytical Thinking',
        'Attention to Detail & Quality Focus',
        'Time Management & Meeting Deadlines',
        'Team Collaboration & Communication',
        'Adaptability & Learning New Technologies Quickly',
        'Critical Thinking & Decision Making',
        'Creativity & Innovation in Solution Design',
    ],
    'skills_philosophy' => 'Choose the right tool for the problem, not the problem for the tool.',
    'projects_subtitle' => 'A collection of mobile applications, machine learning projects, and software solutions showcasing diverse technical skills.',
    'projects' => [
        [
            'title' => 'University Learning Management System App',
            'category' => 'Mobile Apps',
            'description' => 'Developed an Android app with Firebase integration, enabling student feedback submission and lecturer responses. Key features include user authentication, course management, and a feedback system.',
            'problem' => 'Full-stack mobile development',
            'tech' => ['Android Studio', 'Java', 'Firebase', 'Git'],
            'gradient' => 'from-blue-500 to-cyan-500',
            'icon' => 'boxes',
            'url' => null,
            'url_label' => 'View Project',
            'images' => [
                [
                    'src' => 'images/projects/university-lms/login.svg',
                    'alt' => 'LMS app login screen',
                    'caption' => 'Secure login with Firebase authentication',
                ],
                [
                    'src' => 'images/projects/university-lms/dashboard.svg',
                    'alt' => 'LMS student dashboard',
                    'caption' => 'Course dashboard with enrolled modules',
                ],
                [
                    'src' => 'images/projects/university-lms/feedback.svg',
                    'alt' => 'LMS feedback screen',
                    'caption' => 'Student feedback submission and lecturer responses',
                ],
            ],
        ],
        [
            'title' => 'Greenhouse Automation App',
            'category' => 'Mobile Apps',
            'description' => 'Developed a mobile app using Android Studio for full greenhouse automation. Integrated Firebase for data storage and API communication with a machine learning model. Enabled control of IoT devices for real-time environmental management.',
            'problem' => 'Mobile app & IoT integration',
            'tech' => ['Android Studio', 'Java', 'Firebase', 'Machine Learning', 'IoT'],
            'gradient' => 'from-blue-500 to-cyan-500',
            'icon' => 'zap',
            'url' => null,
            'url_label' => 'View Project',
            'images' => [
                [
                    'src' => 'images/projects/greenhouse-automation/dashboard.svg',
                    'alt' => 'Greenhouse control dashboard',
                    'caption' => 'Real-time temperature and humidity monitoring',
                ],
                [
                    'src' => 'images/projects/greenhouse-automation/sensors.svg',
                    'alt' => 'Greenhouse sensor monitoring',
                    'caption' => 'IoT sensor data synced through Firebase',
                ],
            ],
        ],
        [
            'title' => 'Android Application For Sprinkles Bakery',
            'category' => 'Mobile Apps',
            'description' => 'Android application created using Android Studio, Java, and Firebase for bakery management and operations.',
            'problem' => 'Mobile app development',
            'tech' => ['Android Studio', 'Java', 'Firebase', 'Git'],
            'gradient' => 'from-sky-500 to-cyan-500',
            'icon' => 'boxes',
        ],
        [
            'title' => 'Android Application for Milk Shop Management System',
            'category' => 'Mobile Apps',
            'description' => 'Android application created using Android Studio, Java, and a local MySQL database for managing milk shop operations.',
            'problem' => 'Mobile app & database development',
            'tech' => ['Android Studio', 'Java', 'MySQL', 'Local Database'],
            'gradient' => 'from-teal-500 to-sky-500',
            'icon' => 'database',
        ],
        [
            'title' => 'Hostel Management System App',
            'category' => 'Mobile Apps',
            'description' => 'Developed an Android app for hostel management using Android Studio, integrating Firebase for real-time database and authentication, enabling user registration, room allocation, fee tracking, and notifications.',
            'problem' => 'Full-stack mobile development',
            'tech' => ['Android Studio', 'Java', 'Firebase', 'Real-time Database'],
            'gradient' => 'from-blue-500 to-cyan-500',
            'icon' => 'boxes',
        ],
        [
            'title' => 'Face Recognition System',
            'category' => 'Machine Learning',
            'description' => 'Automatically find all the faces in an image. Recognize and manipulate faces from Python and mark attendance using face recognition technology.',
            'problem' => 'Machine learning & computer vision',
            'tech' => ['Python', 'Machine Learning', 'Computer Vision', 'OpenCV'],
            'gradient' => 'from-blue-500 to-cyan-500',
            'icon' => 'brain',
        ],
        [
            'title' => 'Support Vector Machine (SVM Model)',
            'category' => 'Machine Learning',
            'description' => 'Using a machine learning algorithm to solve complex classification, regression, and outlier detection problems with Support Vector Machine implementation.',
            'problem' => 'Machine learning algorithm development',
            'tech' => ['Python', 'Machine Learning', 'SVM', 'Scikit-learn'],
            'gradient' => 'from-sky-500 to-cyan-500',
            'icon' => 'brain',
        ],
        [
            'title' => 'Business Website Development',
            'category' => 'Web Dev',
            'description' => 'Responsive business website built with Next.js and Payload CMS, including advanced authentication and SEO optimization.',
            'problem' => 'Full-stack development',
            'tech' => ['Next.js', 'Payload CMS', 'JWT', 'REST APIs', 'VS Code', 'GitHub', 'Postman'],
            'gradient' => 'from-blue-500 to-cyan-500',
            'icon' => 'code',
        ],
        [
            'title' => 'Custom WordPress Plugin Development',
            'category' => 'Plugins',
            'description' => 'Modular WordPress plugin that refactors legacy business logic into clean, reusable components with better performance and security.',
            'problem' => 'Backend & plugin engineering',
            'tech' => ['WordPress', 'PHP', 'Git', 'WordPress Toolkit'],
            'gradient' => 'from-teal-500 to-sky-500',
            'icon' => 'wrench',
        ],
        [
            'title' => 'E-commerce Website Development',
            'category' => 'E-commerce',
            'description' => 'Tailored e-commerce experience with custom plugins, checkout customization, and UI improvements for higher conversion and trust.',
            'problem' => 'Storefront & plugin customization',
            'tech' => ['WordPress', 'WooCommerce', 'Elementor', 'TypeScript'],
            'gradient' => 'from-sky-500 to-cyan-500',
            'icon' => 'boxes',
        ],
        [
            'title' => 'Patisserie-Rolland',
            'category' => 'Other',
            'description' => 'Enhancements for a production WordPress site, including delivery service integration, theme translation, and admin panel extensions.',
            'problem' => 'Feature implementation & maintenance',
            'tech' => ['WordPress', 'PHP', 'GoLivro integration', 'Custom admin plugins'],
            'gradient' => 'from-blue-500 to-cyan-500',
            'icon' => 'code',
        ],
    ],
    'experience_subtitle' => 'From early internships to production-ready platforms, I have helped design, build, and ship real-world software that solves meaningful problems for teams and businesses.',
    'experience' => [
        [
            'role' => 'Software Engineering Intern',
            'company' => 'Sri Lanka Export Development Board',
            'period' => 'Previous',
            'icon' => 'code',
            'achievements' => [
                'Website Enhancements (Laravel)  : Implemented new features across backend and frontend and refined account management flows.',
                'Mobile App Development (React Native)  : Developed a React Native mobile application bringing the CRM web experience to mobile devices.',
                'Website Development (Laravel) : Designed and developed a Laravel-based website with secure user management and role-based access control.',
            ],
        ],
        [
            'role' => 'Junior Software Developer',
            'company' => 'M Data Zone SA Pvt Ltd',
            'period' => 'Previous',
            'icon' => 'briefcase',
            'achievements' => [
                'Business Website Development (Next.js + Payload CMS): Delivered a fully responsive business website, integrated Payload CMS with custom API endpoints, and implemented JWT authentication with refresh tokens, OTP flows, and API tokens.',
                'Custom WordPress Backend Logic (PHP Plugin Development): Rebuilt complex legacy logic as a dedicated WordPress plugin, modularized business rules, and improved performance and security.',
                'E-commerce Website Development (WordPress + WooCommerce + Elementor): Built a tailored e-commerce experience with custom TypeScript and PHP plugins, improving product management, checkout flow, and UI details.',
            ],
        ],
        [
            'role' => 'Full Stack Developer',
            'company' => 'Litus Group',
            'period' => 'Current',
            'icon' => 'briefcase',
            'achievements' => [
                'Building full-stack solutions and delivering production-ready software for Litus Group.',
            ],
        ],
    ],
    'education_subtitle' => 'Building expertise through academic training in software technology and continuous learning.',
    'education' => [
        [
            'degree' => 'Bachelor of Information and Communication Technology (BICT) Honours',
            'institution' => 'University of Sri Jayewardenepura, Pitipana, Homagama',
            'duration' => '2020 - 2025',
            'achievement' => 'Degree specialized in software technology with a strong interest in backend engineering, data-focused systems, and teaching.',
            'focus_areas' => ['Software Technology', 'Software Engineering', 'Web Development', 'Backend Engineering'],
            'gradient' => 'from-blue-500 to-cyan-500',
            'icon' => 'graduation',
        ],
    ],
    'education_stats' => [
        ['label' => 'Projects Completed', 'value' => '20+', 'icon' => 'rocket'],
        ['label' => 'Technologies Mastered', 'value' => '15+', 'icon' => 'code'],
        ['label' => 'Years of Experience', 'value' => '2+', 'icon' => 'graduation'],
    ],
    'research' => [
        'title' => 'Machine Learning Projects',
        'summary' => 'Built practical machine learning solutions including a Face Recognition System for automated face detection and attendance marking, and a Support Vector Machine (SVM) model for classification, regression, and outlier detection using Python.',
        'highlights' => [
            ['label' => 'Computer Vision', 'value' => 'OpenCV', 'icon' => 'eye'],
            ['label' => 'ML Framework', 'value' => 'Scikit-learn', 'icon' => 'file-text'],
        ],
        'pipeline' => [
            'Data collection & preprocessing',
            'Feature extraction and model training',
            'Face detection and recognition',
            'Classification, validation & deployment',
        ],
        'stats' => [
            ['label' => 'ML Projects', 'value' => '2'],
            ['label' => 'Primary Language', 'value' => 'Python'],
            ['label' => 'Domains', 'value' => 'CV + SVM'],
        ],
    ],
    'impact' => [
        'stats' => [
            ['label' => 'Projects Completed', 'value' => '20+'],
            ['label' => 'Technologies Mastered', 'value' => '15+'],
            ['label' => 'Years of Experience', 'value' => '2+'],
            ['label' => 'Core Skills', 'value' => '6'],
        ],
        'testimonials' => [],
    ],
    'contact' => [
        'heading' => 'Get In Touch',
        'intro' => "Let's build something useful, scalable, and memorable.",
        'description' => 'Whether you have a project in mind, need technical expertise, or just want to connect — I am always open to interesting conversations.',
        'email' => 'nimeshdilshan440@gmail.com',
        'phone' => '0769230572',
        'github' => 'github.com/Dilo1999',
        'github_url' => 'https://github.com/Dilo1999',
        'linkedin' => 'linkedin.com/in/dilshan-senanayaka-7a78a9211',
        'linkedin_url' => 'https://www.linkedin.com/in/dilshan-senanayaka-7a78a9211',
        'location' => 'Colombo, Sri Lanka',
        'cv_url' => null,
    ],
    'nav' => ['Home', 'About', 'Experience', 'Education', 'Projects', 'Skills', 'Contact'],
];
